spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/mall_db?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    name: test
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.example.cgm.entity
  mapper-locations: classpath:mapper/**Mapper.xml
