server:
  port: 8090
java:
  jedis:
    host: 127.0.0.1
    port: 7001
    password:
    timeout: 5000  #连接超时时间
    maxIdle: 50 #最小空闲数  空闲数依据访问缓存的频率设置，如果有较高并发建议设置大些，避免反复销毁创建连接，反之设置小些
    maxWaitMillis: 500 #获取连接最大等待时间，建议不要设置太长时间
    maxTotal: 500 #最大连接数