spring:
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/trade_a?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.example.tradeasseta.entity
  mapper-locations: classpath:mapper/**Mapper.xml
server:
  port: 8091
