spring:
  shardingsphere:
    datasource:
      names: master,slave0,slave1
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3307/mall_db?useSSL=false&useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456
      slave0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3308/mall_db?useSSL=false&useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456
      slave1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3308/mall_db?useSSL=false&useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456
    masterslave:
      name: ms
      master-data-source-name: master
      slave-data-source-names: slave0,slave1
      # 负载均衡
      load-balance-algorithm-type: round_robin
    props:
      sql:
        show: true
mybatis:
  type-aliases-package: com.example.cgm.entity
  mapper-locations: classpath:mapper/**Mapper.xml